---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "172.16.100.100"}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: centos-6.7
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[ga_proxy_google::default]
    attributes:
