name 'ga_proxy_google'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ga_proxy_google'
long_description 'Installs/Configures ga_proxy_google'
version '0.1.0'
